### ISSUE TITLE
How Can I  Define "Enable PerfCheck" in Namelist.rc

### ISSUE THREAD

**Issue by smft** [uturuncoglu/RegESM#18]
Here comes out another question. After successfully compiled all things regesm is needed and a "regesm.x" excutable file is generated, I run regesm with a command like this "mpirun -n 20 ./regesm.x regcm.in_10km bsea.in". However, it comes out an error like this:
**20180424 100531.164 INFO             PET00 Running with ESMF Version 7.1.0r
20180424 100531.167 ERROR            PET00 util/mod_config.F90:181 Not found  - Passing error in return code
20180424 100531.167 ERROR            PET00 regesm.F90:58 Not found  - Passing error in return code
20180424 100531.167 INFO             PET00 Finalizing ESMF
20180424 100628.222 INFO             PET00 Running with ESMF Version 7.1.0r
20180424 100701.114 INFO             PET00 Running with ESMF Version 7.1.0r
20180424 100701.116 ERROR            PET00 util/mod_config.F90:181 Not found  - Passing error in return code
20180424 100701.116 ERROR            PET00 regesm.F90:58 Not found  - Passing error in return code
20180424 100701.116 INFO             PET00 Finalizing `ESMF**`

I checked the ${regesm_dir}/util/mod_config.F90 and find that this error is probably resulted from the missing definition of "EnablePerfCheck".
`      call ESMF_ConfigGetAttribute(cf, enablePerfCheck,                 &
                                   label='EnablePerfCheck:', rc=rc)
      if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU,    &
          line=__LINE__, file=FILENAME)) return`

ALL SEPARATE TESTS FOR REGCM AND ROMS ARE PASSED (regcm-4.6.1,roms is the summer school version).

The link to your regesm user guide seems to be a dead one.

**Comment by smft** [comment]
I compiled all the codes with gnu compiler. It seems that the code is not compatible with intel compile version 2018 update 2 perfectly.

Is regesm compiler sensitive?

**Comment by smft** [comment]
![1cf4e313c745187be6137d23235338fd](https://user-images.githubusercontent.com/13197624/39237096-2b968db2-48ad-11e8-95e4-e08797b489c1.jpg)
Thanks a lot ! RegESM is running in a concurrent mode, while sequential is not working. I think this maybe results from my environment settings. One more thing, I find that regesm's default Coupling Type is ocean -------> atmosphere (explicit) and ATM------->OCN is implicit. But I do not quite understand the other two mode 'Semi-implicit' and 'leap frog' listed in your namelist.rc. Any references? 
Many Thanks!

**Comment by uturuncoglu** [comment]
you might find more information about sequential vs. concurrent and their setup in the Markdown documentation. In semi-implicit the ocean model is one step ahead. So, there is a one coupling time step lag between them. Following figure could demonstrate it,

[Fig03.pdf](https://github.com/uturuncoglu/RegESM/files/1946561/Fig03.pdf)

This is a convention in ESMF side, so to get more information you could check [here](https://earthsystemcog.org/projects/nuopc/advanced#RunSequence).

**Comment by smft** [comment]
Roger that, many thanks and have a nice day!
