### ISSUE TITLE
Failed to compile mod_esmf_esm.F90

### ISSUE THREAD

**Issue by platipodium** [uturuncoglu/RegESM#19]
When building on Darwin.gfortranclang.64.openmpi.ESMF_7_1_0r with 

    ./bootstrap.sh && CC=clang CXX=clang ./configure  && make

I get

    gfortran -Iutil -I/opt/esmf/mod/modg/Darwin.gfortranclang.64.openmpi.ESMF_7_1_0r -I/opt/esmf/include -I/opt/local/include -I/opt/local/include       -O3 -mtune=native -g -O2 -c  mod_esmf_esm.F90
    mod_esmf_esm.F90:113:55:

                                      comp=child, rc=rc)
                                                       1
    Error: There is no specific subroutine for the generic 'nuopc_driveraddcomp' at (1)

**Comment by platipodium** [comment]
Some observations:

(1) There seems to be no problem with ESMF versions, I get the same error on several betas of ESMF_8_0_0; I don't think this is related to macOS

(2) The problem is only with ATM (when I replace ATM with OCN compilation is fine), and it is related to 
the argument `ATM_SetServices`  in the `nuopc_driveraddcomp` call.

(3) I am using `*_void.F90`, so you might not see the error if you always compile `--with-atm`.  The interfaces of the `ATM_SetServices` routines look identical, though with an ESMF_GridComp and Integer rc as arguments.  

Can you try to do a void build?

**Comment by platipodium** [comment]
Yep, that was the problem. Working now. I saw you fixed it upstream as well. Thanks!

**Comment by uturuncoglu** [comment]
That is great! I think i missed it in the first place. So, it is nice that you found it. Anyway, let me know if you have any other problem.
