### ISSUE TITLE
ESMF-MITGCM

### ISSUE THREAD

**Issue by linsson** [uturuncoglu/RegESM#6]
Hi, I downloaded RegESM-1.0.0-beta.2 but it seems I cannot find any mitgcm interface. Where is it supposed to be in the main folder? Is it already stable? I know it's a beta code but I don't know if there are some parts which are rather stable actually.

Thanks in advance.

**Comment by platipodium** [comment]
Dear Ufuk,

when you say ", i could provide to you ROMS ocean model that could also coupled with RegCM using RegESM", are you referring to a special ROMS version or one from the generally distributed ROMS?

**Comment by platipodium** [comment]
For coupling with the Modular System of rShelves and Coasts (www.mossco.de) I would be very interested in a developer (read) access to the unreleased MITgcm c63s) .  Is this possible in any way?

**Comment by uturuncoglu** [comment]
It is not so different from the original ROMS version but yes, it has some modifications to enable coupling.

**Comment by uturuncoglu** [comment]
The MITgcm part of the code is developed with the colaboration of ENEA, Italy and we did not test it completely. We just need to be sure that river coupling is working for MITgcm coupling. I did not get any response from ENEA recently about this issue. After testing and possibly fixing river issue, i think that we could test three component setup (RegCM+MITgcm+HD) and release patch for MITgcm.

**Comment by uturuncoglu** [comment]
You could also contact with Gianmaria Sanino from ENEA about your request. Also note that there is no any ESMF code in the MITgcm side just couple of modifications to use data comes from RegESM. All the code in RegESM and you could access it easily using Git repository.

**Comment by platipodium** [comment]
Thanks, I willl then wait for the  (RegCM+MITgcm+HD) and release patch for MITgcm
